parameters:
  - name: DeployACR
    type: boolean
    default: true
    displayName: Deploy ACR
  - name: PopulateACR
    type: boolean
    default: true
    displayName: Populate ACR
  - name: GitTagVersions
    type: boolean
    default: true
    displayName: Git Tag Versions
  - name: WorkloadAffix
    type: string
    default: do
  - name: ApplicationSufix
    type: string
    default: tce
  - name: Location
    type: string
    default: westeurope
  - name: Environment
    type: string
    default: dev

pr: none

trigger: none

pool:
  vmImage: windows-latest

stages:
  - stage: dev
    jobs:
      - job: BootstrapBicepRegistry
        displayName: Bootstrap Bicep Registry
        steps:

          - task: AzureCLI@2
            displayName: Deploy Azure Resource group
            enabled: true
            condition: eq(${{ parameters.DeployACR }}, 'true')
            inputs:
              azureSubscription: "ServicePrincipal"
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              inlineScript: |
                $WorkloadAffix = "${{ parameters.WorkloadAffix }}"
                $ApplicationSufix = "${{ parameters.ApplicationSufix }}"
                $Location = "${{ parameters.Location }}"
                $Environment = "${{ parameters.Environment }}"

                Write-Host "Creating resource group..."

                $resourceGroup = az deployment sub create `
                    -f "$(Build.SourcesDirectory)/src/iac/az-workloads/bicepregistry/resourcegroup.bicep" `
                    -l $Location `
                    --parameters workloadAffix=$WorkloadAffix applicationSufix=$ApplicationSufix environment="$Environment" `
                    --name resourcegroup-$(Build.BuildId) `
                    -o json | ConvertFrom-Json

                $resourceGroupName = $resourceGroup.Properties.Outputs.resourceGroupName.value

                Write-Host "##vso[task.setvariable variable=resourceGroupName]$resourceGroupName"

          - task: AzureCLI@2
            displayName: Deploy Azure Container Registry
            enabled: true
            condition: eq(${{ parameters.DeployACR }}, 'true')
            inputs:
              azureSubscription: "ServicePrincipal"
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              inlineScript: |
                $WorkloadAffix = "${{ parameters.WorkloadAffix }}"
                $ApplicationSufix = "${{ parameters.ApplicationSufix }}"
                $Location = "${{ parameters.Location }}"
                $Environment = "${{ parameters.Environment }}"

                Write-Host "Creating container registry on Resource Group '$(resourceGroupName)'..."

                $acrDeploy = az deployment group create `
                    -f "./src/iac/az-workloads/bicepregistry/main.bicep" `
                    -g $(resourceGroupName) `
                    --parameters workloadAffix=$WorkloadAffix applicationSufix=$ApplicationSufix instanceNumber=001 environment="$Environment" `
                    | ConvertFrom-Json -Depth 10

                Write-Host $acrDeploy

                $acrId = $acrDeploy.properties.outputs.acrId.value

                Write-Host $acrId

                Write-Host "##vso[task.setvariable variable=acrId]$acrId"

          - task: AzureCLI@2
            displayName: Deploy bicep modules to ACR
            enabled: true
            condition: and(eq(${{ parameters.PopulateACR }}, 'true'), eq(${{ parameters.DeployACR }}, 'true'))
            inputs:
              azureSubscription: "ServicePrincipal"
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              workingDirectory: $(Build.SourcesDirectory)
              inlineScript: |
                Write-Host "Pushing existing modules to ACR '$(acrId)'..."

                $coreModules = "$(Build.SourcesDirectory)/src/iac/az-modules"

                $versionFiles = Get-ChildItem $coreModules -Recurse -Filter "version.json" | Select-Object FullName

                foreach ($versionFilePath in $versionFiles) {
                  Write-Host "Processing $($versionFilePath.FullName)"

                  $versionFile = Get-Content -Raw -Path $versionFilePath.FullName | ConvertFrom-Json

                  Write-Host "Pushing bicep module '$($versionFile.module)' to ACR"

                  Write-Host "Module: '$($versionFile.module)'"
                  Write-Host "Module version: '$($versionFile.version)'"

                  $bicepModule = $versionFilePath.FullName.Replace("version.json", "main.bicep")

                  az bicep publish --file $bicepModule --target "br:$(acrId)/bicep/modules/$($versionFile.module):v$($versionFile.version)"
                }

          - task: AzureCLI@2
            displayName: Deploy bicep Workloads to ACR
            enabled: true
            condition: and(eq(${{ parameters.PopulateACR }}, 'true'), eq(${{ parameters.DeployACR }}, 'true'))
            inputs:
              azureSubscription: "ServicePrincipal"
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              workingDirectory: $(Build.SourcesDirectory)
              inlineScript: |
                Write-Host "Pushing existing modules to ACR '$(acrId)'..."

                $workloads = "$(Build.SourcesDirectory)/src/iac/az-workloads"

                $versionFiles = Get-ChildItem $workloads -Recurse -Filter "version.json" | Select-Object FullName

                foreach ($versionFilePath in $versionFiles) {
                  Write-Host "Processing $($versionFilePath.FullName)"

                  $versionFile = Get-Content -Raw -Path $versionFilePath.FullName | ConvertFrom-Json

                  Write-Host "Pushing bicep module '$($versionFile.module)' to ACR"

                  Write-Host "Module: '$($versionFile.module)'"
                  Write-Host "Module version: '$($versionFile.version)'"

                  $bicepModule = $versionFilePath.FullName.Replace("version.json", "main.bicep")

                  az bicep publish --file $bicepModule --target "br:$(acrId)/bicep/workloads/$($versionFile.module):v$($versionFile.version)"
                }

          - task: AzureCLI@2
            displayName: Tagging bicep modules
            enabled: true
            condition: eq(${{ parameters.GitTagVersions }}, 'true')
            inputs:
              azureSubscription: "ServicePrincipal"
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              workingDirectory: $(Build.SourcesDirectory)
              inlineScript: |
                Write-Host "Loading existing modules and workloads..."

                $coreModules = "$(Build.SourcesDirectory)/src/iac"

                $versionFiles = Get-ChildItem $coreModules -Recurse -Filter "version.json" | Select-Object FullName

                foreach ($versionFilePath in $versionFiles) {
                  Write-Host "Processing $($versionFilePath.FullName)"

                  $versionFile = Get-Content -Raw -Path $versionFilePath.FullName | ConvertFrom-Json

                  $gitTagVersion = "$($versionFile.module)-v$($versionFile.version)"

                  Write-Host "Creating git tag: '$gitTagVersion'"

                  $existingTag = git tag -l $gitTagVersion

                  if($existingTag){
                    Write-Host "##[warning]Version '$gitTagVersion' already exist"
                  }else{
                    Write-Host "Generating tag '$gitTagVersion'"
                    git tag $gitTagVersion
                    git push --tags
                  }
                }
