trigger:
  branches:
    include:
      - master
      - feature/*

pool:
  vmImage: windows-latest

stages:
  - stage: dev
    jobs:
      - job: BicepModulesDeploy
        displayName: Bicep Modules Deploy
        variables:
          - name: revision
            value: $[counter('$(Build.SourceBranch)', 0)]
          - template: /pipelines/config/vars.yml

        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0

          - powershell: |
              if("$(Build.Reason)" -eq "PullRequest")
              {
                $sourceBranch = "$(System.PullRequest.SourceBranch)"
                $branch = "origin/$sourceBranch"
              }
              else
              {
                $sourceBranch = "$(Build.SourceBranch)".Replace("refs/heads/", "origin/")
                $branch = $sourceBranch
              }

              Write-Host "##vso[task.setvariable variable=sourceBranch]$sourceBranch"
              Write-Host "Branch: $sourceBranch"

            displayName: Determine source branch

          - powershell: |
              Write-Host "Validate version file"

              git fetch --all --tags

              $lastTag = git tag --sort=-committerdate -l | Where {$_ -notlike "*pre-release*"  } | Select -First 1

              # if("$(Build.Reason)" -eq "PullRequest")
              # {
              #   $sourceBranch = "$(System.PullRequest.SourceBranch)"
              #   $branch = "origin/$sourceBranch"
              # }
              # else
              # {
              #   $sourceBranch = "$(Build.SourceBranch)".Replace("refs/heads/", "origin/")
              #   $branch = $sourceBranch
              # }

              # Write-Host "Branch: $branch"

              $branch = "$(sourceBranch)"

              Write-Host "Latest tag: $lastTag"

              $versionFile = (git diff --name-only $lastTag $branch) -match "/version.json"

              if($versionFile.Count -gt 1){
                Write-Host $versionFile
                Write-Error "More than one version file updated"

              }elseif($null -eq $versionFile -or $versionFile.Count -eq 0 -or $versionFile -eq $false){
                Write-Error "No version files were updated"
              }

              Write-Host "##vso[task.setvariable variable=versionFileName]$versionFile"
              $versionFile = Get-Content -Raw -Path $versionFile | ConvertFrom-Json

              if($branch -like "*/feature/*"){
                $preRelease = ".$(revision)-pre-release"
                $bicepModuleVersion = $versionFile.version + $preRelease
              }
              else{
                $bicepModuleVersion = $versionFile.version
              }

              Write-Host "Module changed: '$($versionFile.module)'"
              Write-Host "Module version: '$bicepModuleVersion'"

              Write-Host "##vso[task.setvariable variable=bicepModuleVersion]$bicepModuleVersion"
              Write-Host "##vso[task.setvariable variable=bicepModuleName]$($versionFile.module)"

            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Get version"
            enabled: true

          - powershell: |
              Write-Host "Obtaining changed files..."
              $lastTag = git tag --sort=-committerdate -l | Select -First 1

              $branch = "$(Build.SourceBranch)".Replace("refs/heads/", "origin/")

              $changedFiles = (git diff --name-only $lastTag $branch) | Where-Object { $_ -like "*src/iac*" }

              foreach ($file in $changedFiles ) {
                  Write-Host "Validating: '$file'"
                  if ($file -notlike "*/$env:bicepModuleName/*") {
                      Write-Error "Error: Identified changes in a module other than '$env:bicepModuleName'"
                  }
              }
            displayName: Validate changed files
            enabled: true

          - task: AzureCLI@2
            displayName: Deploy bicep modules to ACR
            enabled: true
            inputs:
              azureSubscription: "ServicePrincipal"
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              workingDirectory: $(Build.SourcesDirectory)
              inlineScript: |
                $bicepModule = "$(versionFileName)".Replace("version.json", "main.bicep")
                $acrVersion = "$(bicepModuleName):v$(bicepModuleVersion)"

                Write-Host "Pushing module '$acrVersion' to ACR '$(acrId)'"
                az bicep publish --file $bicepModule --target "br:$(acrId)/bicep/modules/$acrVersion"

          - powershell: |
              $tagVersion = "$env:bicepModuleName-v$env:bicepModuleVersion"
              Write-Host $tagVersion

              $existingTag = git tag -l $tagVersion

              if($existingTag){
                Write-Error "Version '$tagVersion' already exist"
              }

              Write-Host "Generating tag '$tagVersion'"
              git tag $tagVersion

              git push --tags
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Generate git tag"
            enabled: true

          - powershell: |
              $branch = "$(Build.SourceBranch)"

              Write-Host "Removing pre releases of version v$env:bicepModuleVersion"

              $preReleases = git tag --sort=-committerdate -l | Where {$_ -like "$env:bicepModuleName-v$env:bicepModuleVersion*-pre-release" }

              foreach($preRelease in $preReleases){
                Write-Host "Removing pre release version: $preRelease"
                git push --delete origin $preRelease
              }
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Remove pre releases"
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
